config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views.fbv import generate_new_password, verify
from users.views.cbv import LoginView, LogoutView, RegisterView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('verify/', verify, name='verification'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from catalog.models import NULLABLE

# Create your models here.

class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Email')

    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='Номер телефона', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='Страна', **NULLABLE)
    verified = models.BooleanField(default=False, verbose_name='Активация')
    verification_code = models.IntegerField(default=0, verbose_name='Код верификации')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from catalog.forms import StyleFormMixin
from users.models import User


class RegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class ProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'country', 'avatar',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views/cbv.py
from random import randint
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from django.core.mail import send_mail
from django.conf import settings
from users.forms import RegisterForm, ProfileForm
from users.models import User


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):
        new_user = form.save()
        ver_num = randint(1000, 1000000)
        new_user.verification_code = ver_num
        new_user.save()
        send_mail(
            subject='Account activation',
            message=f'Your activation code : {ver_num}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email],
            fail_silently=False
        )
        return super().form_valid(form)


class UserUpdateView(UpdateView):
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = ProfileForm

    def get_object(self, queryset=None):
        return self.request.user

users/views/fbv.py
from random import randint

from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.shortcuts import redirect, render
from django.urls import reverse
from users.models import User

@login_required
def generate_new_password(request):
    new_password = ''.join([str(randint(0, 9)) for _ in range(12)])
    send_mail(
        subject='Вы сменили пароль',
        message=f'Ваш новый пароль: {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email],
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('catalog:catalog'))

def verify(request):
    if request.method == 'POST':
        number = request.POST.get('number')
    try:
        user = User.objects.get(verification_code=number)
        user.verified = True
        user.save()
        return redirect(reverse('users:login'))
    except:
        return render(request, 'users/verification.html')

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card-header">
            Вход в систему
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Вход</button>
            </form>
        </div>
        <div class="card-footer"></div>
    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card-header">
            Регистрация в Магазинчатом магазине
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Регистрация</button>
            </form>
        </div>
        <div class="card-footer"></div>
    </div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card-header">
            Мой профиль
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
        </div>
        <div class="card-footer">
            <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать новый пароль</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/verification.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Активация аккаунта</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Введите код из письма</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" name="number" class="form-control" id="number" placeholder="Ваш номер" required>
                        </div>
                        <input type="submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}