catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import *

app_name = CatalogConfig.name

urlpatterns = [
    path('', CategoryListView.as_view(), name='category'),
    path('contact/', ContactsView.as_view(), name='contacts'),
    path('products/', ProductListView.as_view(), name='products'),
    path('<int:pk>/products/', ProductsCategoryListView.as_view(), name='category_product'),
    path('<int:pk>/products/create/', ProductCreateView.as_view(), name='product_create'),
    path('<int:pk>/position/update/', ProductUpdateView.as_view(), name='product_update'),
    path('<int:pk>/position/updatemoderator/', ProductModeratorUpdateView.as_view(), name='product_update_moderator'),
    path('<int:pk>/position/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('<int:pk>/position/', cache_page(60)(ProductDetailView.as_view()), name='position'),
    path('blogs/', BlogListView.as_view(), name='list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views.fbv import generate_new_password, verify
from users.views.cbv import LoginView, LogoutView, RegisterView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('verify/', verify, name='verification'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
]

catalog/models.py
from django.db import models
from django.conf import settings

# Create your models here.

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    """
    Модель для категорий
    """
    name = models.CharField(max_length=100, verbose_name='Категория')
    description = models.TextField(**NULLABLE, verbose_name='Описание')

    def __str__(self):
        """
        Возвращение строкового представления объекта
        """
        return f"Категория: {self.name}"

    class Meta:
        """
        Настройки для наименования объекта/объектов
        """
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    """
    Модель для продуктов
    """
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    preview = models.ImageField(upload_to='catalog/', **NULLABLE, verbose_name='Превью')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    purchase_price = models.IntegerField(verbose_name='Цена за покупку')
    date_of_creation = models.DateField(verbose_name='Дата создания')
    date_of_last_modification = models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Продавец')
    is_published = models.BooleanField(default=False, verbose_name='Признак публикации')


    def __str__(self):
        """
        Возвращение строкового представления объекта
        """
        return f"{self.category} (Категория: {self.category})"

    class Meta:
        """
        Настройки для наименования объекта/объектов
        """
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('name',)    # Сортировка по наименованию продукта

        permissions = [
            (
                'set_is_published',
                'Can is_published'
            ),
            (
              'set_description',
              'Can description'
            ),
            (
                'set_category',
                'Can category'
            )
        ]



class Version(models.Model):
    """
    Модель для версии продукта
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version_number = models.AutoField(primary_key=True, verbose_name='Номер версии')
    version_name = models.CharField(max_length=100, verbose_name='Наименовании версии')
    is_valid = models.BooleanField(default=True, verbose_name='Признак версии')

    def __str__(self):
        """
        Возвращение строкового представления объекта
        """
        return f'Версия: "{self.version_name}" ({self.version_number}) для продукта {self.product}'

    class Meta:
        """
        Настройки для наименования объекта/объектов
        """
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'
        ordering = ('version_number',)


class Blog(models.Model):
    """
    Модель для блоговой записи
    """
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, **NULLABLE, verbose_name='slug')
    content = models.TextField(**NULLABLE, verbose_name='Содержимое')
    preview = models.ImageField(upload_to='catalog/', **NULLABLE, verbose_name='Превью')
    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        """
        Возвращение строкового представления объекта
        """
        return f'Блог: {self.title}'

    class Meta:
        """
        Настройки для наименования объекта/объектов
        """
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        ordering = ('title',)  # Сортировка по наименованию продукта

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        forbidden_words = ['казино', 'криптовалюта', 'крипта',
                           'биржа', 'дешево', 'бесплатно',
                           'обман', 'полиция', 'радар']
        data_list = cleaned_data.split()
        for el in data_list:
            if el.lower() in forbidden_words:
                raise forms.ValidationError('Вы используете запрещенные слова, не надо так!')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        forbidden_words = ['казино', 'криптовалюта', 'крипта',
                           'биржа', 'дешево', 'бесплатно',
                           'обман', 'полиция', 'радар']
        data_list = cleaned_data.split()
        for el in data_list:
            if el.lower() in forbidden_words:
                raise forms.ValidationError('Вы используете запрещенные слова, не надо так!')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.forms import inlineformset_factory
from django.shortcuts import render, reverse, HttpResponseRedirect
from catalog.forms import ProductForm, VersionForm
from catalog.models import Category, Product, Blog, Version
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView, DetailView
from django.urls import reverse_lazy
from pytils.translit import slugify

from catalog.services import category_cache


# Create your views here.

class CategoryListView(ListView):
    model = Category
    extra_context = {
        'title': 'Категории наших товаров',
        'category_pk': Category('pk'),
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['category'] = category_cache()
        return context_data


class ContactsView(TemplateView):
    template_name = 'catalog/contact.html'
    extra_context = {
        'title': 'Контакты'
    }

    def post(self, request):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')

        print(f"{name} ({phone}): {message}")

        return HttpResponseRedirect(self.request.path_info)

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)


class ProductListView(PermissionRequiredMixin, ListView):
    model = Product
    permission_required = 'catalog.view_product'
    extra_context = {
        'title': 'Полный список наших товаров',
    }


class ProductsCategoryListView(PermissionRequiredMixin, ListView):

    model = Product
    permission_required = 'catalog.view_product'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['category_pk'] = category_item.pk
        context_data['title'] = f'Товары из категории: {category_item.name}'

        return context_data


class ProductDetailView(PermissionRequiredMixin, DetailView):

    model = Product
    permission_required = 'catalog.change_product'


class ProductCreateView(PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.add_product'
    success_url = reverse_lazy('catalog:category')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.change_product'
    success_url = reverse_lazy('catalog:category')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def test_func(self):
        return self.request.user.is_staff

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

class ProductModeratorUpdateView(PermissionRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.change_product'
    success_url = reverse_lazy('catalog:category')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def test_func(self):
        return self.request.user.is_staff

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    model = Product
    permission_required = 'catalog.delete_product'
    success_url = reverse_lazy('catalog:category')


class BlogListView(LoginRequiredMixin, ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ('title', 'content', 'preview',)
    success_url = reverse_lazy('catalog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('title', 'content', 'preview',)
    success_url = reverse_lazy('catalog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:list')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Online shop by Alexander Perov</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">Магазинчатый магазин</h4>
              <p class="text-muted">Привет! Кажется ты попал в магазинчатый магазин, а это значит, что у тебя есть уникальная возможность купить что-нибудь почем-нибудь (при желании на сколько-нибудь сторгуемся).</p>
            </div>
            {% include 'catalog/includes/inc_menu.html' %}
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="{% url 'catalog:category' %}" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Магазинчатый магазин</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <div class="album py-5 bg-light">
        <div class="container">
          {% block content %}
          {% endblock %}
        </div>
      </div>

    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Лифт наверх</a>
        </p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
  </body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p>Вы действительно хотите удалить статью "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-success">Удалить</button>
                        <a href="{% url 'catalog:list' %}">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}

<div class="container">

    <div class="row text-start">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{ object.preview|mediapath }}"
                     alt="Card image cap">
            </div>
            <div class="card-body">
                <p class="card-text"><b>{{ object.title }}</b> ({{ object.slug }}) </p>
                <p class="card-text">{{ object.content }}</p>
            </div>
            <div class="card-footer">
                Просмотры: {{ object.views_count }}
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}

<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'catalog:create' %}">Создать новый блог</a>
</div>

<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top" src="{{ object.preview|mediapath }}"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text"><b>{{ object.title }}</b></p>
                <p class="card-text">{{ object.content|truncatechars:100 }}</p>
                <div class="d-flex justify-content-between align-items-center">
                </div>
                <a href="{% url 'catalog:view' object.pk %}" class="btn btn-sm btn-outline-secondary">Просмотр</a>
                <a href="{% url 'catalog:update' object.pk %}" class="btn btn-sm btn-outline-secondary">Редактировать</a>
                <a href="{% url 'catalog:delete' object.pk %}" class="btn btn-sm btn-outline-secondary">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top"
                 data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text={{ object.name }}"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{ object.description }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'catalog:category_product' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Просмотр</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

catalog/templates/catalog/contact.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>501150115011</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>МО, г. Егорьевск, рядом с фонтаном</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/homepage.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="row">
    {% for object in objects_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text={{ object.name }}"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{ object.description }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'catalog:category_product' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Просмотр</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

catalog/templates/catalog/position.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}

<div class="container">
    {% for object in objects_list %}
 <div class="row text-start">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{ object.preview|mediapath }}"
                     alt="Card image cap">
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text">Название: <b>{{ object.name }}</b></p>
                <p class="card-text">{{ object.category }}</p>
                <p class="card-text">Цена: {{ object.purchase_price|floatformat:2 }} руб.</p>
                <p class="card-text">Описание модели: {{ object.description }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'catalog:contacts' %}" type="button" class="btn btn-sm btn-outline-secondary">Оставить заявку на покупку</a>
                        </div>
                    </div>
            </div>
        </div>
    </div>

    {% endfor %}
</div>

{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p>Вы действительно хотите удалить товар "{{ object.name }}"?</p>
                        <button type="submit" class="btn btn-success">Удалить</button>
                        <a href="{% url 'catalog:category' %}">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}

<div class="container">

    <div class="row text-start">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{ object.preview|mediapath }}"
                     alt="Card image cap">
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text">Название: <b>{{ object.name }}</b></p>
                    <p class="card-text">{{ object.category }}</p>
                    <p class="card-text">Цена: {{ object.purchase_price|floatformat:2 }} руб.</p>
                    <p class="card-text">Описание модели: {{ object.description }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'catalog:contacts' %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Оставить заявку на покупку</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    {% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<div class="row">
    <div class="col-12 mb-5">
        {% if user.verified %}
        <a href="{% url 'catalog:product_create' category_pk %}" type="button"
           class="btn btn-outline-success">Создать</a>
        {% endif %}
    </div>
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            {% if user.is_staff %}
            <img class="card-img-top" src="{{ object.preview|mediapath }}"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{ object.name }}</p>
                <p class="card-text">{{ object.description|truncatechars:100 }}</p>
                <p class="card-text">{{ object.owner|default:"Ничейная" }}</p>
                <li>
                    Версия: {% for version_item in object.version_set.all %}
                    {% if version_item.is_valid %}
                    {{ version_item.version_name }}
                    {% endif %}
                    {% endfor %}
                </li>
            </div>
            <div class="card-footer">
                <a href="{% url 'catalog:position' object.pk %}" type="button" class="btn btn-success">Просмотр</a>
                {% if perms.catalog.change_product and user == object.owner %}
                <a href="{% url 'catalog:product_update' object.pk %}" type="button"
                   class="btn btn-warning">Изменить</a>
                {% else %}
                <a href="{% url 'catalog:product_update_moderator' object.pk %}" type="button"
                   class="btn btn-warning">Редактировать</a>
                {% endif %}
                {% if perms.catalog.delete_product %}
                <a href="{% url 'catalog:product_delete' object.pk %}" type="button" class="btn btn-danger">Удалить</a>
                {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

catalog/templates/catalog/products.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<div class="row">
    {% for object in objects_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top" src="{{ object.preview|mediapath }}"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{ object.name }}</p>
                <p class="card-text">{{ object.description|truncatechars:100 }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'catalog:position' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Просмотр</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}